apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "drone-ci-go-pkg-cache"
spec:
  storageClassName: "nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi