apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apihut.fullname" . }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}