DELETE FROM greets WHERE id > 0;

INSERT INTO greets (created_at,updated_at,sentence,author,tags) values
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'早安！美好的假日开始了😄','MI','凌晨,早上,星期六,星期天'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'周末苦短，及时行乐😎','MI','星期六,星期天,星期五'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'执着于理想，纯粹于当下🤗','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'今天的世界打烊了，晚安🌙','MI','晚上,深夜'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'💪撸起袖子加油干','MI','凌晨,早上'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'我们的征程是星辰大海','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'做世界的水手，奔赴所有港口','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'保持热爱，奔赴山海','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'愿你眼里有光，心里有爱','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'每颗人间烟火，都不要错过','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'心之所向，素履以往','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'愿世俗多点温柔，愿你少点难过','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'与更远的地方，见更亮的光','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'生活明朗，万物可爱','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'永远相信美好的事情即将发生','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'但行好事，莫问前程','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'来日方长，何惧车遥马慢','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'吹不出褶的平静日子，也在发光','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'等风来，不如追风去','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'生活原本沉闷，但跑起来就有风','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'前路浩浩荡荡，万事皆可期待','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'世间美好，与你环环相扣','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'唯有热爱，可抵漫长岁月','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'每一天，遇见更好的自己','MI','晚上,早上,凌晨'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'宇宙山河浪漫，生活点滴温暖','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'有趣都藏在无聊的日子里🍭','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'每个冬天的句号都是春暖花开🌸','MI','冬天'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'好事总会发生在下一个转弯🎢','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'执着于理想，纯粹于当下','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'日子常新，未来不远✨','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'万物皆有裂痕，是光进来的地方','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'生活再平凡，也是限量版✨','MI','通用'),
(datetime(CURRENT_TIMESTAMP,'localtime'),datetime(CURRENT_TIMESTAMP,'localtime'),'不念过往，不惧将来🌈','MI','通用');